INSERT INTO CATEGORY(NAME,DESCRIPTION) VALUES('Cafe','Cà phê');
INSERT INTO CATEGORY(NAME,DESCRIPTION) VALUES('Fastfood','Đồ ăn nhanh');
INSERT INTO CATEGORY(NAME,DESCRIPTION) VALUES('Breakfast','Bữa sáng');
INSERT INTO CATEGORY(NAME,DESCRIPTION) VALUES('Tea','Trà');
INSERT INTO CATEGORY(NAME,DESCRIPTION) VALUES('Beer','Bia');
INSERT INTO CATEGORY(NAME,DESCRIPTION) VALUES('Cream','Kem');